on: [push]
name: Discord Commit
jobs:
 discord_commit:  
  name: discord commit
  runs-on: ubuntu-latest
  steps:
   - name: Discord Commits
     uses: Sniddl/discord-commits@v1.2
     with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_HELPER }}
        message: "<@&716558915118170132>\n\n```Successful commit to {{ github.context.payload.repository.owner.name }}/{{ github.context.payload.repository.name}}```\n> Diff: {{ github.context.payload.compare }}"
        embed: '{ "title": "{{ commit.title }}", "description": "{{ commit.description }}", "url": "{{ commit.url }}", "author": { "name": "{{ commit.author.name }} ({{ commit.author.username }})", "icon_url": "https://avatars.io/gravatar/{{ commit.author.email }}"} }'
